import json

file_path = 'e:/NCKH/Code/Fire_Smoke_Early-Detection/crawl_data.ipynb'
with open(file_path, 'r', encoding='utf-8') as f:
    notebook = json.load(f)

# Code mới để thay thế cho cell số 2
new_code = [
    "import os\n",
    "import time\n",
    "import random\n",
    "import requests\n",
    "from bs4 import BeautifulSoup\n",
    "from selenium import webdriver\n",
    "from selenium.webdriver.chrome.service import Service\n",
    "from selenium.webdriver.chrome.options import Options\n",
    "from webdriver_manager.chrome import ChromeDriverManager\n",
    "\n",
    "def download_image_and_create_label(img_url, img_dir, label_dir, img_name, label_content):\n",
    "    try:\n",
    "        headers = {\n",
    "            \"User-Agent\": \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36\"\n",
    "        }\n",
    "        response = requests.get(img_url, headers=headers, stream=True, timeout=10)\n",
    "        \n",
    "        if response.status_code == 200:\n",
    "            img_path = os.path.join(img_dir, f\"{img_name}.jpg\")\n",
    "            with open(img_path, 'wb') as f:\n",
    "                for chunk in response.iter_content(1024):\n",
    "                    f.write(chunk)\n",
    "            \n",
    "            txt_path = os.path.join(label_dir, f\"{img_name}.txt\")\n",
    "            with open(txt_path, 'w') as f:\n",
    "                f.write(label_content + \"\\n\")\n",
    "                \n",
    "            return True\n",
    "    except Exception as e:\n",
    "        pass\n",
    "    return False\n",
    "\n",
    "def crawl_hard_negatives(target_count=4000):\n",
    "    base_dir = \"0_normal_dataset\"\n",
    "    img_dir = os.path.join(base_dir, \"images\")\n",
    "    label_dir = os.path.join(base_dir, \"labels\")\n",
    "    os.makedirs(img_dir, exist_ok=True)\n",
    "    os.makedirs(label_dir, exist_ok=True)\n",
    "    \n",
    "    print(f\"📁 Dữ liệu sẽ lưu tại: {base_dir}/\")\n",
    "\n",
    "    # CHỈ GIỮ LẠI CÁC TỪ KHÓA LIÊN QUAN TỚI LỬA, KHÓI\n",
    "    # QUY ƯỚC NHÃN:\n",
    "    # 0: chỉ lửa\n",
    "    # 1: chỉ khói\n",
    "    # 2: vừa lửa vừa khói\n",
    "    query_labels = {\n",
    "        \"welding sparks factory\": 0, # Lửa an toàn (tia lửa)\n",
    "        \"restaurant kitchen steam\": 1, # Khói an toàn / Hơi nước\n",
    "        \"industrial welding smoke\": 1,\n",
    "        \"factory steam pipe\": 1,\n",
    "        \"dusty woodworking shop\": 1,\n",
    "        \"indoor vape smoke cloud\": 1,\n",
    "        \"dry ice fog event\": 1,\n",
    "        \"incense smoke indoor\": 1\n",
    "        # Đã loại bỏ các từ khóa nhiễu (đèn báo hiệu) không có khói/lửa\n",
    "    }\n",
    "\n",
    "    chrome_options = Options()\n",
    "    chrome_options.add_argument(\"--disable-gpu\")\n",
    "    chrome_options.add_argument(\"--no-sandbox\")\n",
    "    chrome_options.add_argument(\"user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36\")\n",
    "\n",
    "    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=chrome_options)\n",
    "    \n",
    "    total_downloaded = 0\n",
    "    pages_per_query = 15 \n",
    "\n",
    "    for query, class_id in query_labels.items():\n",
    "        if total_downloaded >= target_count: break\n",
    "            \n",
    "        print(f\"\\n{'='*50}\")\n",
    "        print(f\"🔍 ĐANG QUÉT TỪ KHÓA: '{query}' - Nhãn: {class_id}\")\n",
    "        print(f\"{'='*50}\")\n",
    "        \n",
    "        query_formatted = query.replace(' ', '-')\n",
    "        query_prefix = query.replace(' ', '_')\n",
    "        \n",
    "        # Tạo nội dung nhãn: box giả định bao phủ toàn ảnh (x_center y_center width height)\n",
    "        label_content = f\"{class_id} 0.5 0.5 1.0 1.0\"\n",
    "        \n",
    "        for page in range(1, pages_per_query + 1):\n",
    "            if total_downloaded >= target_count: break\n",
    "                \n",
    "            url = f\"https://www.alamy.com/stock-photo/{query_formatted}.html?page={page}&sortBy=relevant\"\n",
    "            driver.get(url)\n",
    "            time.sleep(random.uniform(2.5, 4.0)) \n",
    "            \n",
    "            scroll_pause_time = 0.8\n",
    "            screen_height = driver.execute_script(\"return window.screen.height;\")\n",
    "            i = 1\n",
    "            while True:\n",
    "                driver.execute_script(f\"window.scrollTo(0, {screen_height} * {i});\")  \n",
    "                i += 1\n",
    "                time.sleep(scroll_pause_time)\n",
    "                \n",
    "                scroll_height = driver.execute_script(\"return document.body.scrollHeight;\")  \n",
    "                if (screen_height * i) > scroll_height:\n",
    "                    break\n",
    "\n",
    "            soup = BeautifulSoup(driver.page_source, \"html.parser\")\n",
    "            images = soup.find_all(\"img\")\n",
    "            \n",
    "            page_count = 0\n",
    "            for img in images:\n",
    "                if total_downloaded >= target_count: break\n",
    "                \n",
    "                src = img.get(\"data-src\") or img.get(\"src\")\n",
    "                \n",
    "                if src and \"alamy\" in src.lower() and (\".jpg\" in src.lower() or \".png\" in src.lower()):\n",
    "                    src = src.split('?')[0]\n",
    "                    \n",
    "                    if src.startswith(\"//\"):\n",
    "                        src = \"https:\" + src\n",
    "                        \n",
    "                    img_name = f\"normal_{query_prefix}_p{page}_{page_count:03d}\"\n",
    "                    \n",
    "                    if download_image_and_create_label(src, img_dir, label_dir, img_name, label_content):\n",
    "                        page_count += 1\n",
    "                        total_downloaded += 1\n",
    "                        \n",
    "                        if total_downloaded % 50 == 0:\n",
    "                            print(f\"  [+] Tiến độ: {total_downloaded}/{target_count} ảnh\")\n",
    "\n",
    "            print(f\"👉 Xong Trang {page} ('{query}'): Lấy được {page_count} ảnh.\")\n",
    "            \n",
    "            if page_count < 3:\n",
    "                print(f\"⚠️ Trang web có thể đã chặn hoặc cạn ảnh. Chuyển từ khóa tiếp theo!\")\n",
    "                break\n",
    "\n",
    "    driver.quit()\n",
    "    print(f\"\\n🎉 HOÀN TẤT NHIỆM VỤ! Tổng số ảnh Hard Negatives đã tải: {total_downloaded}\")\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    crawl_hard_negatives(target_count=4000)\n"
]

notebook['cells'][1]['source'] = new_code

with open(file_path, 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)

print("Đã cập nhật thành công file crawl_data.ipynb (Chỉ tải ảnh có lửa, khói)!")
